### ISSUE TITLE
Invalid formula: ../mod_suexec.rb - "formulae require at least a URL"

### ISSUE THREAD

**Issue by ChapDaddy65** [Homebrew/homebrew-apache#154]
I was installing a fresh copy of Linuxbrew and attempted to ``brew install php71`` when I get this error::

```
[~]$ brew install php71
==> Installing php71 from homebrew/php
==> Tapping homebrew/apache
Cloning into '/home/chap/.linuxbrew/Library/Taps/homebrew/homebrew-apache'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 16 (delta 7), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.
Checking connectivity... done.
Error: Invalid formula: /home/chap/.linuxbrew/Library/Taps/homebrew/homebrew-apache/mod_suexec.rb
formulae require at least a URL
Error: Cannot tap homebrew/apache: invalid syntax in tap!
```

I also tried to install just the suspect ruby file and get this as well:
```
[~]$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-apache/master/mod_suexec.rb
######################################################################## 100.0%
Error: formulae require at least a URL
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/chap/.linuxbrew/Library/Homebrew/formula.rb:235:in `determine_active_spec'
/home/chap/.linuxbrew/Library/Homebrew/formula.rb:189:in `initialize'
/home/chap/.linuxbrew/Library/Homebrew/formulary.rb:84:in `new'
/home/chap/.linuxbrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/home/chap/.linuxbrew/Library/Homebrew/formulary.rb:255:in `factory'
/home/chap/.linuxbrew/Library/Homebrew/extend/ARGV.rb:43:in `block in formulae'
/home/chap/.linuxbrew/Library/Homebrew/extend/ARGV.rb:41:in `map'
/home/chap/.linuxbrew/Library/Homebrew/extend/ARGV.rb:41:in `formulae'
/home/chap/.linuxbrew/Library/Homebrew/cmd/install.rb:104:in `install'
/home/chap/.linuxbrew/Library/Homebrew/brew.rb:94:in `<main>'
```

Here's my ``brew config`` if you want that:
```
[~]$ brew config
HOMEBREW_VERSION: 1.1.8
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: d6371b24895cb4eca83ecedf5f1dbf12743a89a2
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 7d8f4f3925b2f80ae932547b5552e996cd8d7455
Core tap last commit: 52 minutes ago
HOMEBREW_PREFIX: /home/chap/.linuxbrew
HOMEBREW_REPOSITORY: /home/chap/.linuxbrew
HOMEBREW_CELLAR: /home/chap/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: dual-core 64-bit sandybridge
Homebrew Ruby: 2.3.1 => /usr/bin/ruby2.3
Clang: N/A
Git: 2.9.3 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: N/A
Kernel: Linux 4.8.0-22-generic x86_64 GNU/Linux
OS: Ubuntu 16.10
Codename: yakkety
OS glibc: 2.24
OS gcc: 6.2.0
Linuxbrew glibc: N/A
Linuxbrew gcc: 5.3.0
Linuxbrew xorg: N/A
```

I'm assuming that this wont install properly because of Linuxbrew, or being on Linux vs a Mac?

Please advise, Thank you.

**Comment by burknator** [comment]
Same here. Trying to install PHP 5.4 (don't ask). I assume that's because [mod_suexec.rb](https://github.com/Homebrew/homebrew-apache/blob/master/mod_suexec.rb) provides only URLs for different versions of macOS and none for Linux?

**Comment by crayolu** [comment]
anybody solved this yet

**Comment by ChapDaddy65** [comment]
i just started using yaourt since I'm on Arch, I would agree with @burknator that what it's wanting is something that Mac has that linux doesnt.

**Comment by pgerzani** [comment]
If anyone else runs into this, the ruby formula has a check at the top for what version of MacOS is being used to choose the Apache build to grab.  I just added an else with the el capitan version:
> else 
>  url "https://archive.apache.org/dist/httpd/httpd-2.4.16.tar.bz2"
>  sha256 "ac660b47aaa7887779a6430404dcb40c0b04f90ea69e7bd49a40552e9ff13743"
end

and then installed the formula manually.

**Comment by vincentendrahadi** [comment]
@pgerzani can you please explain it step by step?? Thank you

**Comment by gynekolog** [comment]
@vincentendrahadi 
`cd /usr/local/Homebrew/Library/Taps/homebrew`
`git clone https://github.com/Homebrew/homebrew-apache.git`
open cloned homebrew-apache folder and [implement fix](https://github.com/Homebrew/homebrew-apache/pull/172/commits/929a52cb2dc235507aa151334d45eb5042e44a35).

**Comment by vincentendrahadi** [comment]
Thanks @pgerzani

**Comment by vincentendrahadi** [comment]
Thanks @gynekolog

**Comment by Suadvertb** [comment]
@gynekolog  Thanks!I am macOS High Sierra,and It worked for me.

**Comment by zhiqiang21** [comment]
it's work for me @gynekolog

**Comment by MikeMcQuaid** [comment]
This tap is now deprecated, sorry.
